config/routes.rb
Rails.application.routes.draw do
  delete 'user_notifications/destroy'

  post '/auth/:provider/callback' => 'sessions#create'
  get 'activate/:token' => 'users#activate', as: :user_activation
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', as: :logout
  get 'join_group/:id' => 'groups#join', as: :join_group
  get 'group/:group_id/remove_group_member/:member_id' => 'groups#remove_member', as: :remove_group_member
  post 'join_group/:id' => 'users#join_group'
  get 'leave_group/:id' => 'users#leave_group', as: :leave_group
  post 'group_invite' => 'groups#invite', as: :group_invite
  get 'draw_names/:id' => 'groups#draw_names', as: :draw_names
  post 'draw_names/:id' => 'groups#do_draw_names', as: :do_draw_names
  post 'save_sub_groups/:id' => 'groups#save_sub_groups', as: :save_sub_groups
  post 'create_next_collection/:id' => 'groups#create_next_collection', as: :create_next_collection

  resources :users, only: [:edit, :update]
  resources :identities
  resources :item_comments, only: [:create]
  resources :groups
  resources :collections do
    resources :lists do
      resources :items, only: [:new, :edit, :update, :create, :destroy]
    end
  end
  resources :password_resets

  root 'sessions#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :group
  has_many :lists
  has_many :name_drawings

  validates :group_id, presence: true
  validates :name, presence: true

  default_scope { order(name: :desc) }

  obfuscate_id spin: 658165144
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include SessionsHelper
  include ListsHelper

  before_action :is_user_member, only: [:show]

  def index
  end

  def show
    @lists_visible = true

    # Show the list if the collection is not the latest
    latest_collection = @collection.group.collections.first
    if @collection.name == latest_collection.name
      @lists_visible = Time.now.month >= 11
    end

    # Display the current user's list first on the show page
    current_user_lists = @collection.lists.where(user: @current_user)
    other_lists = @collection.lists.where.not(id: current_user_lists)
    @lists = current_user_lists
    @lists += other_lists if @lists_visible

    @list_dropdown = @lists.map { |list| [list.name, name_to_id(list.name)] }
    @list_dropdown.unshift ['Select List', '']

    @name_drawing = @collection.name_drawings.where(picker: @current_user).first

    @user_notifications = UserNotification.where(user: @current_user, is_read: false).all
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def auto_link_text(text)
    auto_link(text, :html => { :target => '_blank' }) do |url|
      truncate(url, :length => 33)
    end
  end
end

app/views/collections/_item_view.html.erb
<% unless current_user == list.user && item.hidden_from_owner %>
  <dt><%= item_link(collection, list, item) %></dt>
  <dd class="item-description">
      <small><%= auto_link_text(item.description) %></small>
      <hr>
  </dd>
<% end %>

app/views/collections/show.html.erb
<% unless @user_notifications.empty? %>
  <div id="notifications-modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">System Updates</h4>
        </div>
        <div class="modal-body">
          <% @user_notifications.each do |user_notification| %>
            <div class="panel panel-primary">
              <div class="panel-heading">
                <%= user_notification.title %>
              </div>

              <div class="panel-body">
                <%= user_notification.message %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="modal-footer">
          <%= button_to "Close", user_notifications_destroy_path, remote: true, method: :delete, class: 'btn btn-primary', params: { ids: @user_notifications.map { |user_notification| user_notification.id } } %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $('#notifications-modal').modal('show');
</script>

<div class="container">
  <div class="page-header">
    <h3><%= @group.name %> - <%= @collection.name %></h3>
  </div>

  <div class="row">
    <div class="col-md-12 visible-xs visible-sm hidden-print">
      <h4>Jump to list: <%= select_tag(:list_navigation, options_for_select(@list_dropdown)) %></h4>
    </div>
  </div>

  <% if @name_drawing %>
    <div class="row">
      <div class="col-md-12">
        <p>
          <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#drawn-name" aria-expanded="false" aria-controls="drawn-name">
            Whose name did you draw?
          </button>
        </p>
        <div class="collapse" id="drawn-name">
          <div class="well">
            <%= @name_drawing.receiver.name %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <% if !@lists_visible %>
    <div class="row">
      <div class="col-md-12">
        <h4>Work on your list now, but all lists will become visible November 1</h4>
      </div>
    </div>
  <% end %>

  <div class='row'>
    <% @lists.each_with_index do |list, index| %>
      <!-- keep 4 lists per row -->
      <% if index > 0 && index % 4 == 0 %>
        </div>
        <div class='row'>
      <% end %>

      <div id='<%= name_to_id(list.name) %>' class='panel panel-default col-md-3'>
          <div class='panel-heading list-header'>
            <div class="panel-title">
              <%= list.name %>
            </div>
          </div>
          <div class="panel-body">
            <p class='owner hidden-print'>Owner: <%= list.user.name if list.user %></p>
            <p class='actions hidden-print'><%= link_to 'Add Item', new_collection_list_item_path(@collection, list), class: 'btn btn-default' %> <%= link_to 'Edit List', edit_collection_list_path(@collection, list), class: 'btn btn-default' %></p>
            <dl>
              <% list.items.each do |item| %>
                <%= render partial: 'item_view', locals: {collection: @collection, list: list, item: item} %>
              <% end %>
            </dl>
            <div class='visible-xs visible-sm back-to-top hidden-print'>
            <%= link_to ' Back to top', '#', class: 'fa fa-arrow-up top-link' %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>