config/routes.rb
Rails.application.routes.draw do
  delete 'user_notifications/destroy'

  post '/auth/:provider/callback' => 'sessions#create'
  get 'activate/:token' => 'users#activate', as: :user_activation
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', as: :logout
  get 'join_group/:id' => 'groups#join', as: :join_group
  get 'group/:group_id/remove_group_member/:member_id' => 'groups#remove_member', as: :remove_group_member
  post 'join_group/:id' => 'users#join_group'
  get 'leave_group/:id' => 'users#leave_group', as: :leave_group
  post 'group_invite' => 'groups#invite', as: :group_invite
  get 'draw_names/:id' => 'groups#draw_names', as: :draw_names
  post 'draw_names/:id' => 'groups#do_draw_names', as: :do_draw_names
  post 'save_sub_groups/:id' => 'groups#save_sub_groups', as: :save_sub_groups
  post 'create_next_collection/:id' => 'groups#create_next_collection', as: :create_next_collection

  resources :users, only: [:edit, :update]
  resources :identities
  resources :item_comments, only: [:create]
  resources :groups
  resources :collections do
    resources :lists do
      resources :items, only: [:new, :edit, :update, :create, :destroy]
    end
  end
  resources :password_resets

  root 'sessions#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :collections
  has_many :group_members
  has_many :members, through: :group_members, source: :user
  has_many :sub_groups
  has_many :sub_group_members, through: :sub_groups, source: :members

  validates :name, presence: true
  validates :question, presence: true
  validates :answer, presence: true
  validates :user_id, presence: true

  obfuscate_id spin: 48151248

  def non_sub_group_members
    members.select { |member| !sub_group_members.include? member }
  end

  def draw_names
    collection = collections.first
    collection.name_drawings.destroy_all
    available_members = sub_group_members.map(&:id)

    sub_group_members.each do |member|
      # temporarily remove members other sub_group_members
      sub_group = sub_groups.select { |g| g.members.include?(member) }
      same_sub_group_members = sub_group.first.members.map(&:id)

      temp_available_members = available_members - same_sub_group_members

      # select random available member
      receiver = temp_available_members[rand(temp_available_members.size)]

      # remove selected member from available_members
      available_members -= [receiver]

      name_drawing = NameDrawing.new
      name_drawing.picker = member
      name_drawing.receiver_id = receiver
      name_drawing.collection = collection
      name_drawing.save
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        current_user.groups << @group

        collection = Collection.new({name: Time.now.year, group: @group})
        collection.save
        format.html { redirect_to groups_path, notice: 'Group created. To invite people to your group, click on the "Options" tab for your group below.'}
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def join
    @user = current_user
    @group = Group.find(params[:id])

    if !@user.active && @user.original_url
      redirect_to root_url, alert: 'You must activate your account before you can join groups'
    end
    if @user.groups.include?(@group)
      redirect_to groups_path, notice: "You are already a member of #{@group.name}"
    end
  end

  def remove_member
    @user = current_user
    @group = Group.find(params[:group_id])
    @member = User.find(params[:member_id])

    respond_to do |format|
      if @group.user == @user
        if @group.members.include?(@member)
          if @group.members.destroy(@member)
            format.html { redirect_to groups_path, notice: "#{@member.name} successfully removed from #{@group.name}" }
          else
            format.html { redirect_to groups_path, alert: "#{@member.name} could not be removed from #{@group.name}" }
          end
        else
          format.html { redirect_to groups_path, alert: "#{@member.name} is not a member of #{@group.name}" }
        end
      else
        format.html { redirect_to groups_path, alert: "You can't remove your self from #{@group.name}" }
      end
    end
  end

  def invite
    user = current_user
    @group = Group.find(params[:group_id])
    emails = params[:group][:emails].split("\r\n")

    respond_to do |format|
      UserMailer.invitation_email(user, @group, emails).deliver
      format.html { redirect_to groups_path, notice: 'Invitation email sent' }
    end
  end

  def draw_names
    @group = Group.find(params[:id])
  end

  def save_sub_groups
    @group = Group.find(params[:id])
    @group.sub_groups.destroy_all

    params[:sub_groups].each do |group|
      member_ids = group[1].map(&:to_i)
      members = User.where(id: member_ids)

      sub_group = @group.sub_groups.create
      sub_group.members = members
      sub_group.save
    end

    redirect_to :draw_names
  end

  def do_draw_names
    @group = Group.find(params[:id])
    @group.draw_names
    redirect_to :draw_names
  end

  def create_next_collection
    @group = Group.find(params[:id])

    last_collection = @group.collections.first
    new_collection = @group.collections.create(name: last_collection.name.to_i + 1)

    last_collection.lists.each do |list|
      new_collection.lists << List.create(user_id: list.user_id, name: list.name)
    end

    redirect_to new_collection
  end

  private

  def group_params
    params.require(:group).permit(:name, :question, :answer)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/draw_names.html.erb
<div class="container">
  <div class="draw-names-actions">
    <%= form_tag save_sub_groups_path(@group.to_param), id: 'save-sub-groups-form' do %>
      <%= submit_tag 'Save Sub-Groups', class: 'btn btn-default', method: :post %>
    <% end %>
    <%= form_tag do_draw_names_path(@group.to_param) do %>
      <%= submit_tag 'Draw Names', class: 'btn btn-default', method: :post %>
    <% end %>
  </div>
  <div class="names-container">
    <div class="sub-group default-group">
      <h5>
        These members will not draw names
      </h5>
      <ul id="sortable-0" class="sortable">
        <% @group.non_sub_group_members.each do |member| %>
          <li data-member-id="<%= member.id %>" class="ui-state-default">
            <%= member.name %>
          </li>
        <% end %>
      </ul>
    </div>

    <% @group.sub_groups.each_with_index do |sub_group, index| %>
      <div class="sub-group">
        <h5>Group <%= index + 1 %></h5>
        <ul id="sortable-<%= index + 1 %>" class="sortable">
          <% sub_group.members.each do |member| %>
            <li data-member-id="<%= member.id %>" class="ui-state-default">
              <%= member.name %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="sub-group">
      <h5>New Group</h5>
      <ul id="sortable-<%= @group.sub_groups.size + 1 %>" class="sortable empty">
      </ul>
    </div>
  </div>
</div>

<ul>
  <% @group.collections.first.name_drawings.each do |drawing| %>
    <li><%= drawing.picker.name %> -> <%= drawing.receiver.name %></li>
  <% end %>
</ul>

app/views/groups/index.html.erb
<div class="container">
  <% unless current_user.active %>
    <div class="page-header">
      <h3>You need to activate your account first</h3>
    </div>
  <% else %>
    <div class="page-header">
      <h3><%= current_user.name %>'s Groups</h3>
    </div>

    <% if @groups.empty? %>
      <p>You don't have any groups, <%= link_to "create one", new_group_path %> and get started!</p>
    <% else %>
      <div class="row">
        <% @groups.each_with_index do |group, index| %>
          <!-- keep 3 groups per row -->
          <% if index > 0 && index % 3 == 0 %>
            </div>
            <div class='row'>
          <% end %>

          <div class="panel panel-default col-md-4">
            <div class="panel-heading">
              <div class="panel-title"><%= group.name %></div>
            </div>
            <div class="panel-body">
              <ul class="nav nav-tabs">
                <li class="active"><a href="#<%= group.to_param %>-lists" data-toggle="tab">Lists</a></li>
                <li><a href="#<%= group.to_param %>-members" data-toggle="tab">Members</a></li>
                <li class="options-link"><a href="#<%= group.to_param %>-options" data-toggle="tab">Options</a></li>
              </ul>

              <div class="tab-content">
                <div id="<%= group.to_param %>-lists" class="tab-pane fade in active">
                  <ul class="list-group">
                    <% if group.user == current_user %>
                      <li class="list-group-item">
                        <%= link_to 'Create Next Collection', create_next_collection_path(group.to_param), method: :post %>
                      </li>
                    <% end %>
                    <% group.collections.each do |collection| %>
                        <%= link_to collection, class: 'list-group-item'  do %>
                          <%= collection.name %>
                          <span class="badge">View</span>
                        <% end %>
                    <% end %>
                  </ul>
                </div>
                <div id="<%= group.to_param %>-members" class="tab-pane fade">
                  <ul class="list-group">
                    <% if group.user == current_user %>
                      <div class="draw-names-button">
                        <%= link_to 'Draw Names', draw_names_path(group), class: 'btn btn-default' %>
                      </div>
                    <% end %>
                    <p>
                      <% group.members.each do |member| %>
                        <li class="list-group-item"><%= member.name %> <%= link_to 'Remove', remove_group_member_path(group, member), data: { confirm: 'Are you sure?' } , class: 'badge' if group.user == current_user && current_user != member %></li>
                      <% end %>
                    </p>
                  </ul>
                </div>
                <div id="<%= group.to_param %>-options" class="tab-pane fade options-tab">
                  <div class="invite-button">
                    <a href="#" class='btn btn-default group-invite-link' data-id="<%= group.to_param %>" data-toggle='modal' data-target='#invite-modal'>Invite by Email</a> or send the link below
                  </div>
                  <div class="input-group group-join-link" data-toggle="tooltip" title="Share this link to invite people to this group">
                    <input id="<%= group.to_param %>-url" class="form-control" value="<%= join_group_url(group) %>" readonly />
                    <span class="input-group-addon clipboard-button" data-clipboard-target='<%= group.to_param %>-url' title="copy to clipboard"><i class="fa fa-files-o fa-fw"></i></span>
                  </div>
                  <p>
                    <%= link_to 'Leave Group', leave_group_path(group), data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' unless group.user == current_user %>
                  </p>
                </div>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="modal fade" id="invite-modal" tabindex="-1" role="dialog" aria-labelledby="invite-modal-title" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="invite-modal-title">Group Invite</h4>
      </div>
      <%= form_tag group_invite_path, class: 'form-horizontal' do %>
        <%= hidden_field_tag :group_id %>
        <div class="modal-body">
          <div class="form-group">
            <label class="col-sm-4 control-label" for="emails">
              Email Addresses
              <i class="fa fa-question-circle" data-toggle="tooltip" title="Enter one email address per line"></i>
            </label>
            <div class="col-sm-8">
              <%= text_area_tag("group[emails]", nil, size: "20x6", class: 'form-control') %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag 'Send email', class: 'btn btn-primary' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/groups/join.html.erb
<div class="col-md-5">
  <%= form_tag("/join_group/#{@group.to_param}", method: "post", class: 'form-horizontal') do %>
    <fieldset>
      <div class="page-header"><h3>Joining <%= @group.name %></h3></div>

      <% if @group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@group.errors.count, "error") %> prohibited this list from being saved:</h2>

          <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <label class="col-sm-2 control-label">Question</label>
        <div class='col-sm-10'>
          <span class="form-control"><%= @group.question %></span>
        </div>
      </div>

      <div class='form-group'>
        <label for="answer" class="col-sm-2 control-label">Answer</label>
        <div class='col-sm-10'>
          <input type="text", id="answer", name="answer" class="form-control" />
        </div>
      </div>
    </fieldset>

    <div class='form-group'>
      <div class="col-sm-offset-2 col-sm-10">
        <%= submit_tag 'Join', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="col-md-5">
  <%= form_for @group, html: { class: 'form-horizontal' } do |f| %>
    <fieldset>
      <div class="page-header">
        <h3>New Group</h3>
      </div>

      <% if @group.errors.any? %>
        <div class='error_explanation'>
          <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :name, class: 'col-sm-3 control-label' do %>
          Name
          <i class="fa fa-question-circle" data-toggle="tooltip" title="Give this group a name"></i>
        <% end %>
        <div class='col-sm-9'>
          <%= f.text_field :name, placeholder: "Group name", class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :question, class: 'col-sm-3 control-label' do %>
          Question
          <i class="fa fa-question-circle" data-toggle="tooltip" title="A question only group members should be able to answer"></i>
        <% end %>
        <div class='col-sm-9'>
          <%= f.text_field :question, placeholder: "Question (Something only group members know)", class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :answer, class: 'col-sm-3 control-label' do %>
        Answer
        <i class="fa fa-question-circle" data-toggle="tooltip" title="Answer to the secret question"></i>
        <% end %>
        <div class='col-sm-9'>
          <%= f.text_field :answer, placeholder: "Group question's answer", class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
      <div class="col-sm-offset-3 col-sm-9">
          <%= f.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...' } %>
          <%= link_to 'Cancel', groups_path, class: 'btn btn-default' %>
        </div>
      </div>

    </fieldset>

  <% end %>
</div>