config/routes.rb
Rails.application.routes.draw do
  delete 'user_notifications/destroy'

  post '/auth/:provider/callback' => 'sessions#create'
  get 'activate/:token' => 'users#activate', as: :user_activation
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', as: :logout
  get 'join_group/:id' => 'groups#join', as: :join_group
  get 'group/:group_id/remove_group_member/:member_id' => 'groups#remove_member', as: :remove_group_member
  post 'join_group/:id' => 'users#join_group'
  get 'leave_group/:id' => 'users#leave_group', as: :leave_group
  post 'group_invite' => 'groups#invite', as: :group_invite
  get 'draw_names/:id' => 'groups#draw_names', as: :draw_names
  post 'draw_names/:id' => 'groups#do_draw_names', as: :do_draw_names
  post 'save_sub_groups/:id' => 'groups#save_sub_groups', as: :save_sub_groups
  post 'create_next_collection/:id' => 'groups#create_next_collection', as: :create_next_collection

  resources :users, only: [:edit, :update]
  resources :identities
  resources :item_comments, only: [:create]
  resources :groups
  resources :collections do
    resources :lists do
      resources :items, only: [:new, :edit, :update, :create, :destroy]
    end
  end
  resources :password_resets

  root 'sessions#index'

end

app/models/item.rb
require 'httparty'
require 'uri'

class Item < ActiveRecord::Base
  belongs_to :list
  has_many :item_comments

  validates :name, presence: true
  validates :list, presence: true
  validates :description, length: { maximum: 256 }
  # validates :hidden_from_owner, presence: true

  obfuscate_id spin: 546518432

  has_attached_file :image,
    styles: { medium: "300x300>", thumb: "100x100>" },
    default_url: '/images/no_image.png',
    url: '/item_images/:id/:basename_:style.:extension'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  before_validation :shorten_urls

  def image_url=(url)
    self.image = URI.parse(url)
  end

  def shorten_urls
    unless description.nil?
      urls = URI.extract(description)
      urls.each do |url|
        result = HTTParty.get("https://api-ssl.bitly.com/v3/shorten?access_token=#{ENV['BITLY_TOKEN']}&longUrl=#{url}")
        next if result.fetch('status_code') == 500
        short_url = result.fetch('data', {})['url']

        description.gsub!(url, short_url) unless short_url.nil?
      end
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ListsHelper
  include SessionsHelper

  before_action :is_user_member
  before_action :set_list
  before_action :set_item, only: [:edit, :update, :destroy]

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.list = @list

    respond_to do |format|
      if @item.save
        format.html { redirect_to collection_url(@collection, anchor: name_to_id(@item.list.name)), notice: 'Item created' }
      else
        format.html { render action: 'new'}
      end
    end
  end

  def update
    if params[:remove_image]
      remove_image
    else
      respond_to do |format|
        if @item.update(item_params)
          format.html { redirect_to collection_url(@collection, anchor: name_to_id(@item.list.name)), notice: 'Item updated' }
        else
          format.html { render action: 'edit' }
        end
      end
    end
  end

  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to collection_url(@collection, anchor: name_to_id(@item.list.name)), notice: 'Item deleted' }
    end
  end

  def remove_image
    @item.image = nil

    respond_to do |format|
      if @item.save
        format.html { redirect_to edit_collection_list_item_path(@collection, @list, @item), notice: 'Image removed' }
      else
        format.html { redirect_to edit_collection_list_item_path(@collection, @list, @item), alert: 'Image removed failed' }
      end
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_list
    @collection = Collection.find(params[:collection_id])
    @list = List.find(params[:list_id])
    @item_comment = ItemComment.new
  end

  def item_params
    params.require(:item).permit(:name, :description, :hidden_from_owner, :purchased, :purchased_by, :image)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="col-md-10">
  <%= form_for([@collection, @list, @item], html: {class: 'form-horizontal', multipart: true}) do |f| %>
    <fieldset>
      <div class="page-header">
        <h3><% if params[:action] == 'new' %>
          New Item for <%= @list.name %>
        <% else %>
          Editing <%= @item.name %>
        <% end %></h3>
      </div>

      <% if @item.errors.any? %>
        <div class='error_explanation'>
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li><%= raw msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :name, class: 'col-sm-4 control-label' do %>
          Name
          <i class="fa fa-question-circle" data-toggle="tooltip" title="Give this item a name"></i>
        <% end %>
        <div class='col-sm-8'>
          <%= f.text_field :name, placeholder: "Item name", class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :description, class: 'col-sm-4 control-label' do %>
          Description
          <i class="fa fa-question-circle" data-toggle="tooltip" title="Enter a description of the item (optional)"></i>
        <% end %>
        <div class='col-sm-8'>
          <%= f.text_area :description, placeholder: "Item description", class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
        <label class='col-sm-4 control-label'>
          Image
          <i class="fa fa-question-circle" data-toggle="tooltip" title="Current image for this item"></i>
        </label>
        <div class='col-sm-8'>
          <%= image_tag @item.image.url(:medium) %>
        </div>
        <div class='col-sm-offset-4 col-sm-8'>
          <%= f.submit 'Remove Image', class: 'btn btn-danger remove-image-button', name: 'remove_image', data: { disable_with: 'Please wait...' } %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :image, class: 'col-sm-4 control-label toggle-image-label' do %>
          Choose Image
          <i class="fa fa-question-circle" data-toggle="tooltip" title="Browse your device for an image of the item (optional)"></i>
        <% end %>
        <%= f.label :image, class: 'col-sm-4 control-label toggle-image-label hidden' do %>
          New Image Url
          <i class="fa fa-question-circle" data-toggle="tooltip" title="Enter an address for a new image (optional)"></i>
        <% end %>
        <div class='col-sm-8'>
          <div class="input-group">
            <span class="input-group-btn">
              <span class="btn btn-default btn-file">
                  Browse <%= f.file_field :image, accept: "image/*", class: 'image-browse' %>
              </span>
            </span>
            <input type="text" value='No image selected' class="form-control" readonly>
          </div>

          <%= f.text_field :image, value: nil, class: 'form-control image-url hidden', disabled: true %>
          <span class="help-block hidden-xs hidden-sm toggle-image">Need to use a URL instead?</span>
        </div>
      </div>

      <% unless current_user == @list.user %>
        <hr>
        <h3>The following items are not visible to <%= @list.username || "list owner" %></h3>
        <div class='form-group'>
          <label class="col-sm-4 control-label">
            Hide item from list owner? (Selecting Yes will hide the entire item from the list owner only. Other users will see the item with a <i class="fa fa-exclamation-circle"></i>
            <i class="fa fa-question-circle" data-toggle="tooltip" title="Hide this item from list owner (optional)"></i>
          </label>
          <div class='col-sm-8 item-checkbox'>
            <div class="onoffswitch">
              <%= f.check_box :hidden_from_owner, class: 'checkbox onoffswitch-checkbox hide-item-checkbox' %>
              <label class="onoffswitch-label" for="item_hidden_from_owner">
                  <span class="onoffswitch-inner"></span>
                  <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>

        <div class='form-group'>
          <label class="col-sm-4 control-label">
            Has item been purchased?
            <i class="fa fa-question-circle" data-toggle="tooltip" title="Has this item been purchased? (optional)"></i>
          </label>
          <div class='col-sm-8 item-checkbox'>
            <div class="onoffswitch">
              <%= f.check_box :purchased, class: 'checkbox onoffswitch-checkbox purchased-checkbox' %>
              <label class="onoffswitch-label" for="item_purchased">
                  <span class="onoffswitch-inner"></span>
                  <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
        </div>

        <div class='form-group'>
          <%= f.label :purchased_by, class: 'col-sm-4 control-label' do %>
            Purchased by
            <i class="fa fa-question-circle" data-toggle="tooltip" title="Who purchased the item? (optional)"></i>
          <% end %>
          <div class='col-sm-8'>
            <%= f.text_field :purchased_by, placeholder: "Name of person who bought item", class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class='item-comments'>
            <label class='col-sm-4 control-label'>Comments</label>
            <div class='col-sm-8'>
              <% @item.item_comments.each do |comment| %>
                <% if !comment.private || (comment.private && comment.user == current_user) %>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <%= comment.user.name %><%= " (Private)" if comment.private %><%= " -- #{time_ago_in_words(comment.created_at)} ago" %>
                    </div>
                    <div class="panel-body">
                      <%= comment.comment %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class='form-group'>
          <div class="col-sm-offset-4 col-sm-8">
            <% if params[:action] == 'new' %>
              <p>You must create the item before leaving comments</p>
            <% else %>
              <a href="#" class='btn btn-default' data-toggle='modal' data-target='#comment-modal'>Add New Comment</a>
            <% end %>
          </div>
        </div>
      <% end %>

    <div class='form-group'>
      <div class="col-sm-offset-4 col-sm-8">
        <%= f.submit class: 'btn btn-primary', data: { disable_with: 'Please wait...' } %>
        <%= link_to 'Delete Item', collection_list_item_path(@collection, @list, @item), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger' unless @item.id.nil? %>
        <%= link_to 'Cancel', collection_path(@collection), class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

<% unless current_user == @list.user %>
  <div class='modal fade' id='comment-modal' tabindex="-1" role='dialog' aria-labelledby="comment-modal-title" aria-hidden="true">
    <div class='modal-dialog'>
      <div class='modal-content'>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="comment-modal-title">Add New Comment</h4>
        </div>
        <%= form_for(@item_comment, html: {class: 'form-horizontal'}) do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :item_id, value: @item.to_param %>
          <%= hidden_field_tag :collection_id, @collection.to_param %>
          <div class="modal-body">

            <div class='form-group'>
              <%= f.label :comment, class: 'col-sm-3 control-label' do %>
                Comment
                <i class="fa fa-question-circle" data-toggle="tooltip" title="Enter a comment for the item"></i>
              <% end %>
              <div class='col-sm-9'>
                <%= f.text_area :comment, class: 'form-control' %>
              </div>
            </div>

            <div class='form-group'>
              <label class="col-sm-3 control-label">
                Private?
                <i class="fa fa-question-circle" data-toggle="tooltip" title="Keep this comment private to you?"></i>
              </label>
              <div class='col-sm-9 item-checkbox'>
                <div class="onoffswitch">
                  <%= f.check_box :private, class: 'checkbox onoffswitch-checkbox private-comment-checkbox' %>
                  <label class="onoffswitch-label" for="item_comment_private">
                      <span class="onoffswitch-inner"></span>
                      <span class="onoffswitch-switch"></span>
                  </label>
                </div>
              </div>
            </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Add Comment', class: 'btn btn-primary', data: { disable_with: 'Please wait...' } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/new.html.erb
<%= render 'form' %>