config/routes.rb
Rails.application.routes.draw do
  delete 'user_notifications/destroy'

  post '/auth/:provider/callback' => 'sessions#create'
  get 'activate/:token' => 'users#activate', as: :user_activation
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', as: :logout
  get 'join_group/:id' => 'groups#join', as: :join_group
  get 'group/:group_id/remove_group_member/:member_id' => 'groups#remove_member', as: :remove_group_member
  post 'join_group/:id' => 'users#join_group'
  get 'leave_group/:id' => 'users#leave_group', as: :leave_group
  post 'group_invite' => 'groups#invite', as: :group_invite
  get 'draw_names/:id' => 'groups#draw_names', as: :draw_names
  post 'draw_names/:id' => 'groups#do_draw_names', as: :do_draw_names
  post 'save_sub_groups/:id' => 'groups#save_sub_groups', as: :save_sub_groups
  post 'create_next_collection/:id' => 'groups#create_next_collection', as: :create_next_collection

  resources :users, only: [:edit, :update]
  resources :identities
  resources :item_comments, only: [:create]
  resources :groups
  resources :collections do
    resources :lists do
      resources :items, only: [:new, :edit, :update, :create, :destroy]
    end
  end
  resources :password_resets

  root 'sessions#index'

end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= @tracking_id %>', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Christmas Lists</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= render "layouts/google_analytics" if Rails.env.production? %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='navbar navbar-default navbar-static-top' role='navigation'>
    <div class='container'>
      <div class='navbar-header'>
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
          <span class="navbar-link">Menu</span>
        </button>
        <%= link_to 'Christmas Lists', root_url, class: 'navbar-brand' %>
      </div>


      <div class='collapse navbar-collapse'>
        <ul class='nav navbar-nav'>
          <li class="divider"></li>
          <li>
             <%= link_to 'View My Groups', groups_path %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to 'Create New List', new_collection_list_path(@collection) if params[:controller] == "collections" and params[:action] == "show" %>
            <%= link_to 'Create New Group', new_group_path if params[:controller] == "groups" and params[:action] == "index" %>
          </li>
        </ul>
        <ul class='nav navbar-nav navbar-right'>
          <% if current_user.provider == 'identity' %>
            <li class="divider"></li>
            <li>
              <%= link_to 'Change Password', edit_user_path(current_user) %>
            </li>
          <% end %>
          <li class="divider"></li>
          <li>
            <%= link_to "Logout #{current_user.name}", logout_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class='container'>
    <%= render partial: "shared/flash_messages", flash: flash %>
    <div class='row'>
      <%= yield %>
    </div>
  </div>
</body>
</html>